openapi: 3.0.0
info:
  title: Lazuardy API Documentation
  description: Dokumentasi API untuk backend Lazuardy
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Local Server

tags:
  - name: Authentication
    description: Endpoint untuk Login, Register, dan OAuth
  - name: Payment Gateway
    description: Hal-hal yang berkaitan dengan keuangan

paths:
  /auth/{provider}/redirect:
    get: 
      tags:
        - Authentication
      summary: Redirect ke Authentikasi OAuth
      parameters:
        - name: provider
          in: path
          required: true
          description: google, facebook
          schema:
            type: string
      responses:
        '200':
          description: Berhasil redirect

  /auth/{provider}/callback:
    get:
      tags:
        - Authentication
      summary: Callback dari OAuth
      parameters:
        - name: provider
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Berhasil callback
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/AuthSuccess'
                  - $ref: '#/components/schemas/OAuthUserNew'

  /login:
    post:
      tags:
        - Authentication
      summary: Login secara manual
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "user@example.com"
              password: "password123"
      responses:
        '200':
          description: Berhasil login
          content:
            application/json:
              example:
                status: "success"
                access_token: "1|wdadubwab..."
                token_type: "Bearer"
        '422':
          $ref: '#/components/responses/ValidationError'

  /logout:
    post:
      tags:
        - Authentication
      summary: Logout akun
      responses: 
        '200':
          description: "berhasil logout"
          content:
            application/json:
              example:
                status: success

  /studentRegister:
    post:
      tags:
        - Authentication
      summary: Mendaftarkan user siswa baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, name, class_id, gender, date_of_birth, telephone_number, province, regency, district, subdistrict]
              properties:
                email: { type: string, format: email, example: "lazuardy.tester@example.com" }
                password: { type: string, format: password, example: "password123" }
                name: { type: string, example: "Lazuardy Student" }
                class_id: { type: integer, example: 12 }
                gender: { type: string, enum: [male, female], example: "male" }
                date_of_birth: { type: string, format: date, example: "2005-08-17" }
                telephone_number: { type: string, example: "081234567890" }
                province: { type: string, example: "Jawa Timur" }
                regency: { type: string, example: "Malang" }
                district: { type: string, example: "Lowokwaru" }
                subdistrict: { type: string, example: "Tulusrejo" }
                google_id: { type: string, nullable: true, example: null }
                facebook_id: { type: string, nullable: true, example: null }
      responses:
        '201':
          description: Berhasil mendaftar
          content:
            application/json:
              example:
                status: success
                access_token: "2|A2fWUPOSpp425YJHftCcnMcSYVNVD8CbLrNhoZr79a0046d6"
                token_type: "Bearer"
        '500':
          description: Gagal Mendaftarkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: {type: string, example: error}
                  message: {type: string, example: Gagal melakukan registrasi siswa.}

  /tutorRegister:
    post:
      tags:
        - Authentication
      summary: Mendaftarkan user tutor baru (dengan upload file)
      requestBody:
        required: true
        content:
          multipart/form-data: # Menggunakan multipart karena ada file
            schema:
              type: object
              required: 
                - email
                - password
                - name
                - gender
                - description
                - date_of_birth
                - telephone_number
                - bank_code
                - account_number
                - province
                - regency
                - district
                - subdistrict
                - subject_id
                - learning_method
                - schedules
                - curriculum_vitae
                - id_card
                - certificate
              properties:
                email: { type: string, format: email }
                password: { type: string, format: password }
                name: { type: string }
                gender: { type: string, enum: [male, female] }
                description: { type: string, description: "Bio singkat tutor" }
                date_of_birth: { type: string, format: date }
                telephone_number: { type: string }
                bank_code: { type: string }
                account_number: { type: string }
                province: { type: string }
                regency: { type: string }
                district: { type: string }
                subdistrict: { type: string }
                google_id: { type: string, nullable: true }
                facebook_id: { type: string, nullable: true }
                subject_id: { type: integer, description: "ID dari mata pelajaran" }
                learning_method: 
                  type: array
                  items: { type: string }
                  example: ["online", "offline"]
                schedules:
                  type: array
                  items:
                    type: object
                    properties:
                      day: { type: string, example: "Monday" }
                      time: { type: string, example: "14:00" }
                curriculum_vitae: { type: string, format: binary, description: "File PDF" }
                id_card: { type: string, format: binary, description: "File PDF/JPG/PNG" }
                certificate: { type: string, format: binary, description: "File PDF" }
      responses:
        '201':
          description: Berhasil mendaftar
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: {type: string, example: success}
                  access_token: {type: string, example: 1|2TWUJufoTJOoGuCepg4s5MNiwAFd1pWTOV7da5JP7761d325}
                  token_type: {type: string, example: Bearer}
        '500':
          description: Gagal Mendaftarkan
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: {type: string, example: error}
                  message: {type: string, example: Gagal melakukan registrasi tutor.}
        '422':
          $ref: '#/components/responses/ValidationError'

  /banks:
    get:
      tags:
        - Payment Gateway
      summary: Mendapatkan daftar bank
      responses:
        '200':
          description: Berhasil
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: "success" }
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Bank'

  /validateBankAccount:
    post:
      tags:
        - Payment Gateway
      summary: Memvalidasi nomor rekening
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [bank_code, account_number]
              properties:
                bank_code: { type: string, example: "ID_BSI" }
                account_number: { type: string, example: "1234567890" }
      responses:
        '200':
          description: Validasi rekening berhasil/gagal
          content:
            application/json: 
              examples:
                SuccessCondition:
                  value: { status: "success", account_holder_name: "FETCH_HOLDER_NAME" }
                ValidationFailed:
                  value: { status: "error", message: "Gagal memverifikasi rekening", error_code: "API_ERROR" }

components:
  responses:
    ValidationError:
      description: Validasi Gagal
      content:
        application/json:
          example:
            message: "Data tidak valid"
            errors:
              email: ["Email sudah terdaftar"]

  schemas:
    Bank:
      type: object
      properties:
        bank_code: { type: string, example: "ID_ALLO" }
        bank_name: { type: string, example: "Allo Bank Indonesia" }

    AuthSuccess:
      type: object
      properties:
        status: { type: string, example: "success" }
        data:
          type: object
          properties:
            message: { type: string, example: "Authorized" }
            access_token: { type: string }
            token_type: { type: string, example: "Bearer" }

    OAuthUserNew:
      type: object
      properties:
        status: { type: string, example: "success" }
        data:
          type: object
          properties:
            message: { type: string, example: "Unauthorized" }
            name: { type: string }
            email: { type: string }
            provider_id: { type: string }