openapi: 3.0.0
info:
  title: Lazuardy API Documentation
  description: Dokumentasi API untuk backend Lazuardy
  version: 1.0.0

servers:
  - url: http://localhost:8000/api
    description: Local Server

tags:
  - name: Authentication
    description: Endpoint untuk Login, Register, dan OAuth

paths:
  /auth/{provider}/redirect:
    get: 
      tags:
        - Authentication
      summary: Redirect ke Authentikasi OAuth
      parameters:
        - name: provider
          in: path
          required: true
          description: google, facebook
          schema:
            type: string
      responses:
        '200':
          description: Berhasil redirect ke OAuth (Tidak mengembalikan api apapun ke backend)

  /auth/{provider}/callback:
    get:
      tags:
        - Authentication
      summary: Callback dari OAuth
      parameters:
        - name: provider
          in: path
          required: true
          description: google, facebook
          schema:
            type: string
      responses:
        '200':
          description: Berhasil callback (Dua skema data)
          content:
            application/json:
              schema:
                oneOf:
                
                  # SKEMA 1: User lama/Terdaftar (Lengkap dengan Token)
                  - type: object
                    properties:
                      status: { type: string, example: "success" }
                      data:
                        type: object
                        properties:
                          message: { type: string, example: "Authorized" }
                          access_token: { type: string, example: "1|wdadubwab..." }
                          token_type: { type: string, example: "Bearer" }

                  # SKEMA 2: User baru (Hanya data dasar dari Google/FB)
                  - type: object
                    properties:
                      status: { type: string, example: "success" }
                      data: 
                        type: object
                        properties:
                          message: { type: string, example: "Unauthorized" }
                          name: { type: string, example: "user" }
                          email: { type: string, example: "user@example.com" }
                          provider_id: { type: string, example: "1092837" }
                          email_verified_at: { type: string, format: date-time, nullable: true }

                  
        '401':
          description: Gagal callback
          content:
            application/json:
              example:
                status: "error"
                message: "dwadb"

  /login:
    post:
      tags:
        - Authentication
      summary: Login secara manual
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "user@example.com"
              password: "password123"
      responses:
        '200':
          description: Berhasil login
          content:
            application/json:
              example:
                status: "success"
                access_token: "1|wdadubwab..."
                token_type: "Bearer"
                
        '422':
          $ref: '#/components/responses/ValidationError' # Menggunakan referensi agar rapi
  /logout:
    post:
      tags:
        - Authentication
      summary: Logout akun
      responses: 
        '200':
          description: "berhasil logout"
          content:
            application/json:
              example:
                status: success

  /requestOtpEmail:
    post:
      tags:
        - Authentication
      summary: Meminta OTP untuk email
      requestBody: 
        required: true
        content: 
          application/json:
            example:
              email: "user@gmail.com"
      responses:
        '201':
          description: "Berhasil mengirim OTP ke email"
          content:
            application/json:
              example:
                status: success
        '500':
          description: "Gagal mengirim OTP ke email"
          content:
            application/json:
              example:
                status: error
                message: pesan error
  /verifyOtpEmail:
    post:
      tags:
        - Authentication
      summary: Verifikasi OTP email dari user
      requestBody: 
        required: true
        content:
          application/json:
            example:
              email: user@gmail.com
              otp: "032398"
      responses: 
        '200':
          description: Berhasil verifikasi OTP email
          content:
            application/json:
              example:
                status: 'success/failed'
        '404':
          description: OTP untuk email tidak ditemukan
          content:
            application/json:
              example:
                status: error
                message: error message

  /studentRegister:
    post:
      tags:
        - Authentication
      summary: Mendaftarkan user siswa baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [email, password, name, class, gender, date_of_birth, telephone_number, province, regency, district, subdistrict]
              properties:
                email: { type: string, format: email, example: "lazuardy.tester@example.com" }
                password: { type: string, format: password, example: "password123" }
                name: { type: string, example: "Lazuardy Developer" }
                class_id: { type: integer, example: 12 }
                gender: { type: string, enum: [Laki-laki, Perempuan], example: "Laki-laki" }
                date_of_birth: { type: string, format: date, example: "2005-08-17" }
                telephone_number: { type: string, example: "081234567890" }
                province: { type: string, example: "Jawa Timur" }
                regency: { type: string, example: "Malang" }
                district: { type: string, example: "Lowokwaru" }
                subdistrict: { type: string, example: "Tulusrejo" }
                google_id: { type: string, nullable: true, example: null }
                facebook_id: { type: string, nullable: true, example: null }
      responses:
        '201':
          description: Berhasil mendaftar
          content:
            application/json:
              example:
                status: success
                access_token: 2|A2fWUPOSpp425YJHftCcnMcSYVNVD8CbLrNhoZr79a0046d6
                token_type: "Bearer" 
        '500':
          description: Terjadi kesalahan internal server (Database error, dsb)
          content:
            application/json:
              example:
                status: "error"
                message: "Gagal melakukan registrasi, silakan cek kembali data Anda."
          

components:
  responses:
    ValidationError:
      description: Validasi Gagal
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
              errors:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: string
          example:
            message: "Kresidensial yang diberikan salah"
            errors:
              email: ["Kresidensial yang diberikan salah"]

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "user"
        email:
          type: string
          format: email
          example: "user@example.com"
        email_verified_at:
          type: string
          format: date-time
          nullable: true
          example: "2026-03-05T00:00:00.000000Z"
        role:
          type: string
          example: "student"
        telephone_number:
          type: string
          nullable: true
          example: "085..."
        google_id:
          type: string
          nullable: true
        facebook_id:
          type: string
          nullable: true
        profile_photo_url:
          type: string
          nullable: true
        date_of_birth:
          type: string
          format: date
          nullable: true
          example: "2000-01-01"
        gender:
          type: string
          nullable: true
        religion:
          type: string
          nullable: true
        home_address:
          type: string
          nullable: true
        latitude:
          type: number
          format: float
          nullable: true
          example: 11.2231
        longitude:
          type: number
          format: float
          nullable: true
          example: 21.2231
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time